DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_insight;
DROP TABLE IF EXISTS asset;
DROP TABLE IF EXISTS asset_metric;
DROP TABLE IF EXISTS asset_meta;
DROP TABLE IF EXISTS user_asset_relation;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  --permission TINYINT NOT NULL,
  --flagged BOOL NOT NULL DEFAULT false,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE
);


CREATE TRIGGER tr_validate_email
  BEFORE INSERT ON user
BEGIN
  SELECT
    CASE
      WHEN NEW.email NOT LIKE '%_@__%.__%' THEN
   	    RAISE (ABORT,'Invalid email address')
    END;
END;


CREATE TRIGGER tr_user_update
  AFTER UPDATE ON user
FOR EACH ROW
BEGIN
   UPDATE user SET updated = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;


CREATE TABLE user_insight (
  user_id INTEGER NOT NULL,
  --session_count INTEGER NOT NULL DEFAULT 0,
  --track the asset queries made by user,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE,
  FOREIGN KEY (user_id) REFERENCES user (id)
);


CREATE TABLE asset (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  ticker TEXT UNIQUE NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE
);


CREATE TABLE asset_metric (
  asset_id INTEGER NOT NULL,
  type TEXT NOT NULL,
  year YEAR NOT NULL,
  quarter TINYINT,
  value FLOAT NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE,
  FOREIGN KEY (asset_id) REFERENCES asset (id)
);


CREATE TABLE asset_meta (
  asset_id INTEGER NOT NULL,
  exchange TEXT NOT NULL,
  sector TEXT NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE,
  FOREIGN KEY (asset_id) REFERENCES asset (id)
);


CREATE TABLE user_asset_relation (
  user_id INTEGER NOT NULL,
  asset_id INTEGER NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TEXT DEFAULT NONE,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (asset_id) REFERENCES asset (id)
)