DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS asset;
DROP TABLE IF EXISTS metric;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE asset (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker TEXT UNIQUE NOT NULL,
  exchange TEXT NOT NULL,
  sector TEXT NOT NULL
);

CREATE TABLE metric (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  asset TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  type TEXT NOT NULL,
  year YEAR NOT NULL,
  quarter TINYINT,
  value FLOAT NOT NULL,
  FOREIGN KEY (asset) REFERENCES asset (id)
);